.TH "playersMenu" 3 "Version 2.0" "Trabalho de Final de PDS2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playersMenu \- Menu de jogadores\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <playersMenu\&.hpp>\fP
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBplayersMenu\fP ()"
.br
.RI "Menu de jogadores\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Menu de jogadores\&. 
.SH "Construtores e Destrutores"
.PP 
.SS "playersMenu::playersMenu ()"

.PP
Menu de jogadores\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Trabalho de Final de PDS2 a partir do código fonte\&.
